### ISSUE TITLE
Regarding repackaging AEPP to a simplified interface for the end user. 

### ISSUE THREAD

**Issue by yoyo6022** [adobe/aepp#11]
Is there any consideration for implementing a module-based design for AEPP enhancement in the future? A module-based design, similar to packages like Pandas, would allow importing the entire AEPP package and making all its modules and contents accessible. For instance, when importing Pandas as 'pd', it provides access to all the functions. This design choice allows you to perform various operations without explicitly calling different classes under the pandas library. I'm curious if there are plans to explore such a design approach for AEPP. (In the case of Pandas library, it imports all the classes in the __init__.py file for the end user. Which makes the library so popular with even Python beginners. Although I'm uncertain about the level of development effort this would require for AEPP).

**Comment by pitchmuc** [comment]
Thanks @yoyo6022 for this idea. 
This is not in the current roadmap but there are works planned that could align with this objective. We will let you know if we ever start working on this.
