### ISSUE TITLE
aepp and app builder

### ISSUE THREAD

**Issue by mdonke** [adobe/aepp#19]
We're thinking about future usage of aepp in context of [App Builder](https://business.adobe.com/de/products/experience-manager/developer-app-builder.html)
As far as I understand App Builder doesn't support Python. Are there any thoughts or Adobe discussions about that?

**Comment by skanjila** [comment]
@mdonke I will see if I can find the internal team at Adobe and speak with them about building a bridge between app builder and python

**Comment by sarahxxu** [comment]
Hi @mdonke this is Sarah from the App Builder team. could you tell us a bit more about what you are looking to build?

**Comment by mdonke** [comment]
Hi Sarah,

we have developed command line tooling for AEP based on this Python aepp library.
We are thinking about adding an UI to that. Obvious first idea was to use App Builder, but then I realized that App Builder only runs Node at the moment. That's why I'm curious if you think that a combination of AEPP and App Builder is a somewhat strange idea or if it could make sense.

**Comment by rezpe** [comment]
Adobe runtime could serve as a proxy to Python code running in the browser. The lib can be fully run on the browser with Pyscript (https://pyscript.net/). However, it can not do web calls to other server, other than the one being hosted on. This could be solved if the calls are done to the Adobe Io runtime and then the runtime forward the calls to AEP ...

**Comment by mdonke** [comment]
Thanks for your answers. We will not pursui this further.
