### ISSUE TITLE
Can not delete profiles via profile API because merge policy can not be provided as an argument.

### ISSUE THREAD

**Issue by benedikt-buchert** [adobe/aepp#27]
### Expected Behavior

deleteEntity should delete the profile. A merge policy should be provided or set as a default value so the API successfully can delete the profile.

### Actual Behavior

`{'message': 'The provided merge policy is not found.  Provide a valid merge policy and try again.', 'statusCode': 422, 'type': 'http://ns.adobe.com/aep/errors/UPLIB-101221-404', 'title': 'The provided merge policy is not found.  Provide a valid merge policy and try again.', 'error-code': 'UPLIB-101221-404', 'error-message': 'The provided merge policy is not found.  Provide a valid merge policy and try again.', 'status': 422}`

#### Sample Code that illustrates the problem

```
myProfiles.deleteEntity(
            schema_name=schema,
            entityId=entityID,
            entityIdNS=ENITTY_ID_N
)
```

**Comment by benedikt-buchert** [comment]
Interesting, it is stated here that it is non-mandatory. I'm still getting this message, though. Also, not 100% sure what it does.

https://developer.adobe.com/experience-platform-apis/references/profile/#tag/Entities/operation/deleteEntity

**Comment by benedikt-buchert** [comment]
Hm, figured it out. It could not find a profile with this merge policy. So this should be turned into a feature request to be able to provide the merge policy.

**Comment by pitchmuc** [comment]
Hello Benedikt, 
I think the possibility to pass merge Policy ID was not available at first when this method was wrapped. 
Hence the option is not available as a parameter :( 
We will try to provide a release in the next weeks to support that, feel free to PR it as well if it is blocking you. 

Best,

**Comment by benedikt-buchert** [comment]
I figured out it works without providing the merge policy. It is just informing you about the error in the response.

I'm still not sure what the merge policy does when sending a delete though.

**Comment by pitchmuc** [comment]
Yeah, I am not sure either... It may be that you have no real default merge policy and you are stitching always with dataset precedence. 
But I am not sure why no one would have the timestamp as default merge policy. 
If not urgent, it will wait another release then :D

**Comment by pitchmuc** [comment]
Fix in the latest release
