### ISSUE TITLE
uploadSmallFile in ingestion.py fails with file open error

### ISSUE THREAD

**Issue by samujob** [adobe/aepp#29]
### Expected Behaviour
uploadSmallFile function should work correctly when ingesting data using .json file
### Actual Behaviour
It fails with file not found error. This happens in the following code within the function

```
if type(data) == str:
            if '.json' in data:
                with open(Path(path),'r') as f:
                    data = json.load(f)
```

It fails because it is trying to open file at **path** instead it should try to open the file passed in **data** (if it is a .json file), for e.g. as follows:
```
if type(data) == str:
            if '.json' in data:
                with open(Path(data),'r') as f:
                    data = json.load(f)
```
### Reproduce Scenario (including but not limited to)
NA
#### Steps to Reproduce
ingestor = ingestion.DataIngestion()
ingestor.uploadSmallFile(batch_id,dataSetId, filename,"./files/profiles.json")
ingestor.uploadSmallFileFinish(batch_id, "COMPLETE")
#### Platform and Version
NA
#### Sample Code that illustrates the problem
ingestor = ingestion.DataIngestion()
ingestor.uploadSmallFile(batch_id,dataSetId, filename,"./files/profiles.json")
ingestor.uploadSmallFileFinish(batch_id, "COMPLETE")
#### Logs taken while reproducing problem
NA

**Comment by pitchmuc** [comment]
Thanks for this report. @samujob 

Sorry for typo. 
We will try to fix it in the next release. 

I hope you are not stuck, it would be possible to load the JSON in the python environment and send the data directly via this function.
